# Generated by Django 2.1 on 2018-08-31 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
