# Generated by Django 2.1 on 2018-08-31 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0003_delete_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='Description',
            field=models.CharField(default='1', max_length=250),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='PhoneNumber',
            field=models.CharField(default='1', max_length=250),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='percentage',
            field=models.CharField(default='1', max_length=250),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='qualification',
            field=models.CharField(default='1', max_length=250),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='subjects',
            field=models.CharField(default='1', max_length=250),
        ),
    ]
