# Generated by Django 2.1 on 2018-08-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20180831_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='Description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='PhoneNumber',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='percentage',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='qualification',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='subjects',
            field=models.CharField(default='', max_length=250),
        ),
    ]
