# Generated by Django 2.1 on 2018-09-03 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20180831_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(default='', max_length=256)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Student_profile')),
            ],
        ),
    ]
