# Generated by Django 2.1 on 2018-09-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_auto_20180903_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby_details',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.Student_profile'),
        ),
    ]
