# Generated by Django 2.1 on 2018-09-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_auto_20180903_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
