# Generated by Django 2.1 on 2018-09-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_student_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby_details',
            name='student',
        ),
        migrations.AlterField(
            model_name='hobby_details',
            name='hobby',
            field=models.CharField(max_length=255),
        ),
    ]
