# Generated by Django 2.1 on 2018-09-07 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_auto_20180907_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby_details',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.Student_profile'),
        ),
        migrations.AlterField(
            model_name='hobby_details',
            name='hobby',
            field=models.CharField(max_length=256),
        ),
    ]
