# Generated by Django 2.1 on 2018-09-07 06:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_auto_20180907_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby_details',
            name='hobby',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None), size=None),
        ),
    ]
